version: '3.7'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-storage
    ports:
      - "9000:9000"   # API S3-compatible
      - "9001:9001"   # Consola web
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio-data:/data  # Datos persistentes en tu disco local
    command: server /data --console-address ":9001"
